package com.manishk.sse;// Generated by Numerix on 04/06/2017 se-demo

public class JerseySseClient {
    //Test comment
    public static void main(String[] args) {
        System.out.println("test");
    }
}
